### ISSUE TITLE
Create a link that opens in given locale

### ISSUE THREAD

**Issue by renatolond** [tootsuite/joinmastodon#105]
It would be nice to have a link that already opens with a given locale. Something in the query string would already be enough, a subdomain would be perfect :)

**Comment by renatolond** [comment]
@Gargron was this fixed or dropped? I still can't seem to find a way to pass the link with a predefined language

**Comment by Krinkle** [comment]
This is possible via the `lang` query parameter. However, it is not promoted (the address bar does not update when selecting a language), which means without looking at [the source code](https://github.com/tootsuite/joinmastodon/blob/9edf69a45d2702b498ee97534506c5f6c2528dc0/src/reducer.js#L13-L51) it can be hard to guess what the right value is (e.g. `nl` vs `nl-NL`).

It also appears to malfunction currently as it only affects the navigation menu. The rest of the page is only translated if you open the page without `lang?=` and select it from the menu. I've reported this bug at https://github.com/tootsuite/joinmastodon/issues/130
