### ISSUE TITLE
How to register on source.joinmastodon.org

### ISSUE THREAD

**Issue by neotrak** [tootsuite/joinmastodon#138]
It's good to see mastodon on https://source.joinmastodon.org/mastodon/joinmastodon eventually may able to move https://github.com/tootsuite/mastodon to it. @Gargron 
May i know how to register on https://source.joinmastodon.org/users/sign_in ? and mastodon.online credentials doesn't work for it

**Comment by Gargron** [comment]
I intend to discontinue the GitLab for multiple reasons, you should not register on it.

**Comment by neotrak** [comment]
> I intend to discontinue the GitLab for multiple reasons, you should not register on it.

What? i don't see any reason to discontinue it. you already came-up with good idea and put them on own instance but strange reasons have bothered to stop it. honestly i can't guess good reason. i don't use this comment to ask why and wait; maybe you'll not say but there's important thing you should care seriously so i say something my own

- Maintain cost? - i don't think; i also have and there're other solutions https://gitea.io/
- Spam control? - eg: issues. many simple solutions others use for that if has prob from it.
- Many things to maintain? -  i can't accept it. you must capable/adjust to handle it. mastodon also grows with time.
- Doubt to secure? - i believe it is ;) if complicated to ensure safety of these additional resources then it look like something bad will happen to(on) main servers later.

The reason for raise aggressive comment (or feel upset comment even if it wasn't exact) for this, just we've lot of hopes on this open source project and it's unhappy to hear someday on news about, "mastodon breached: millions of records published somwhere or something else worst for this project to loss attraction" i know this's also on-premise solution but mainly drive from your hosted solution.
