### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mkljczk** [tootsuite/joinmastodon#24]
I can't find any info how is joinmastodon licensed…

**Comment by koyuawsmbrtn** [comment]
I would suggest the license Mastodon itself uses: GNU Affero General Public License v3.0

**Comment by TheLastProject** [comment]
Can this be reopened? There is still no LICENSE file in this repo or anywhere in the README. It's still unclear what license this is under, so for now we can only assume it's proprietary.
