### ISSUE TITLE
Cloudflare email protection

### ISSUE THREAD

**Issue by ProgVal** [tootsuite/joinmastodon#26]
Hi,

When Javascript is not enabled, the “How it works” contains:

> Each user account has a globally unique name (e.g. @[[email protected]](https://joinmastodon.org/cdn-cgi/l/email-protection))”.

This is probably caused by [Cloudflare's email obfuscation](https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-).
As it does not seem to be needed on joinmastodon, could you disable it?

**Comment by Gargron** [comment]
Done!
