### ISSUE TITLE
The wizard component doesn't get re-rendered when the locale is being changed

### ISSUE THREAD

**Issue by eramdam** [tootsuite/joinmastodon#33]
Small GIF of what's happening

![kapture 2017-09-17 at 4 58 15](https://user-images.githubusercontent.com/1409924/30517584-dff72cc2-9b64-11e7-8c42-35ec132406d9.gif)

**Comment by Gargron** [comment]
Fixed!

**Comment by SerCom-KC** [comment]
Request for reopen: exact same issue occurred again.
