### ISSUE TITLE
Chinese/Japanese font-family are not able to be "font-weight: 500"

### ISSUE THREAD

**Issue by Neetshin** [tootsuite/joinmastodon#39]
Thanks for merge Japanese translation 👍 

Btw its SCSS seems to specified `font-weight` as `500` for `<strong>` elements. I think it's nice design, 
But sadly Chinese/Japanese characters usually doesn't have deference between `font-weight: 400` and `500`.

#### Screenshot:
<img width="477" alt="2017-09-17 16 33 10" src="https://user-images.githubusercontent.com/19276905/30520174-f1a136f0-9bc5-11e7-9cf9-ea0397227eef.png">

Because we're using over 2000 characters and some are not supported such as 500, 700 etc. (If a designer designed 2000 letters in nine ways from 100 to 900, they must die.)

Anyway, could you change the strong element's style for `font-weight: 600` / or apply a language-specific class such as `.ja` to parent elements such as `body` and apply styles appropriate for each languages?

**Comment by Gargron** [comment]
Fixed!
