### ISSUE TITLE
Compress Images?

### ISSUE THREAD

**Issue by ashfurrow** [tootsuite/joinmastodon#55]
Hey there! What are your thoughts on compressing images to save bandwidth and improve page speed? Here's a summary of results I got from non-lossy compression: 

![screen shot 2017-10-21 at 2 01 04 pm](https://user-images.githubusercontent.com/498212/31854493-498c97c6-b668-11e7-812b-49522b9ab27c.png)

And here's what it looks like with lossy compression:

![screen shot 2017-10-21 at 2 02 13 pm](https://user-images.githubusercontent.com/498212/31854506-733206ce-b668-11e7-89f5-802186b15dd1.png)

Personally I think the lossiness look identical enough for the savings, and we could review the before/after in a PR. Just let me know which one you want and I'll send a PR.

**Comment by Gargron** [comment]
@ashfurrow Sure go ahead! Thanks!
