### ISSUE TITLE
Remove national flags in the language selector

### ISSUE THREAD

**Issue by ghost** [tootsuite/joinmastodon#74]
I suppose that the national flags in the language selector should be removed, because

* The national flag of the United Kingdom is representing for English language.
* The national flag of United Arab Emirates is representing for Arabic language.

But many other countries speaks these languages.

**Comment by hakaba-hitoyo** [comment]
> The problem with using flags as symbols for language choice is that some languages are spoken in many countries.

https://www.nngroup.com/articles/flag-problems/
