### ISSUE TITLE
Sign up wizard categories are redundant

### ISSUE THREAD

**Issue by trwnh** [tootsuite/joinmastodon#81]
For the part where you choose "I am a ...", some of the choices return exactly the same results. For example, "a developer" and "a sysadmin" is exactly the same set of instances. 

Perhaps either collapse this into a more generalistic "techie" category, or rethink the usage of categories? Invariably, there will be some overlap between use-cases and some niches might be much closer than others.

**Comment by Gargron** [comment]
This is 100% intended as part of the design.
