### ISSUE TITLE
Sponsor on Liberapay

### ISSUE THREAD

**Issue by jelv** [tootsuite/joinmastodon#82]
9 months ago Mastodon joined [Liberapay](https://liberapay.com/Mastodon) to accept donations. This is a open source and non-profit donation platform for libre creators and project like Mastodon. Could the link to Liberapay also be added beside the Patreon option? 

"Become a sponsor" on the [homepage](https://joinmastodon.org) and the [sponsor page](https://joinmastodon.org/sponsors) now links only to Patreon. This could be changed to "Sponsor on Patreon" and second button "Sponsor on Liberapay".

[Mastodon's profile on Liberapay](https://liberapay.com/Mastodon).

**Comment by Gargron** [comment]
The problem is, I can't put the people who pledge on Liberapay on the sponsors page because Liberapay pledges are anonymous.

**Comment by jelv** [comment]
For the simplicity sponsors maybe is better. Another option could be that you change it to a fund the project page and add the also missing paypal and bitcoin options.

**Comment by skyfaller** [comment]
It's no longer true that all Liberapay pledges are anonymous. When I go into Receiving > Patrons > Visibility Levels, it says "Liberapay supports three visibility levels for donations. Each level can be turned on or off, but at least one of them must be enabled." The three options are:

- Allow secret donations
- Allow private donations
- Allow public donations

So you should be able to set Liberapay to only accept public donations if that's the way you want it.

But why don't you want anonymous donors?
