### ISSUE TITLE
CSS: sponsors aren't appropriately sized at <800px widths

### ISSUE THREAD

**Issue by trwnh** [tootsuite/joinmastodon#86]
![image](https://user-images.githubusercontent.com/10606431/37846729-92674b06-2e9c-11e8-86ee-29c42f95699c.png)

**Comment by Gargron** [comment]
Has this been fixed and I forgot to tag the issue, did the browser fix its implementation, or what is the reason for closing this issue?

**Comment by trwnh** [comment]
Not sure -- if you changed it from multicol to flexbox, then you fixed it and forgot. At least that's what I assumed happened.

**Comment by trwnh** [comment]
Reopening because it looks even more broken on mobile https://imgur.com/a/TNjhKvr

Chrome 68 on an Xperia X Compact (viewport 424x625)

**Comment by trwnh** [comment]
![mobile landscape 625px](https://i.imgur.com/3jJ8K0Y.png)
![mobile portrait 424px](https://i.imgur.com/36oJk8w.png)

**Comment by trwnh** [comment]
Ideally, `.sponsorship .sponsors-list--badges li` shouldn't have a width off 33.3%; it should be a static px or em width because the information inside the li should not be proportional.

**Comment by trwnh** [comment]
Also not technically the same issue but similarly caused by poor breakpoints: 
![image](https://user-images.githubusercontent.com/10606431/40567692-0c2215d6-603c-11e8-8be7-91b028670749.png)

**Comment by trwnh** [comment]
Somewhat unrelated issue that is also caused by viewport width: long names in the regular Sponsors list causes the row heights to become out-of-sync.
![image](https://user-images.githubusercontent.com/10606431/40567802-97118cf8-603c-11e8-930a-4d8cce26b746.png)
