### ISSUE TITLE
How to get our instance listed here?

### ISSUE THREAD

**Issue by pierreozoux** [tootsuite/joinmastodon#93]
thanks!

**Comment by Gargron** [comment]
The data comes from instances.social where you can sign up to be listed. Our list is sorted by number of recently active users and cut-off at 60 items per category. Open registrations and at least v2.1.2 are required to show up also.

**Comment by Gargron** [comment]
I can add any language you want to the dropdown. I'm just not adding all possible ones straight away because if there's 0 servers, it's useless. I'll add the Finnish one :P
