### ISSUE TITLE
Open source the "What is Mastodon" video

### ISSUE THREAD

**Issue by picsi** [tootsuite/joinmastodon#94]
Pinging @Gargron 

While not a joinmastodon issue per se, I couldn't find another way to request this, so: please release the What is Mastodon video under YouTube's CC BY license, so that it can be reuploaded into Wikipedia or the Internet Archive.

https://www.youtube.com/watch?v=IPSbNdBmWKE

**Comment by Gargron** [comment]
Done

**Comment by picsi** [comment]
Awesome, check out the end result: https://commons.wikimedia.org/wiki/File:What_is_Mastodon.webm
